// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pkg/proto/flago.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFlagReq_Family int32

const (
	CreateFlagReq_UNIVERSAL_DISABLED CreateFlagReq_Family = 0
	CreateFlagReq_UNIVERSAL_ENABLED  CreateFlagReq_Family = 1
	CreateFlagReq_PERCENTAGE_OF      CreateFlagReq_Family = 2
	CreateFlagReq_COMBINATION_OF     CreateFlagReq_Family = 3
	CreateFlagReq_SET_OF             CreateFlagReq_Family = 4
	CreateFlagReq_REFERENCE_TYPE     CreateFlagReq_Family = 5
	CreateFlagReq_NOT_SET_OF         CreateFlagReq_Family = 6
)

// Enum value maps for CreateFlagReq_Family.
var (
	CreateFlagReq_Family_name = map[int32]string{
		0: "UNIVERSAL_DISABLED",
		1: "UNIVERSAL_ENABLED",
		2: "PERCENTAGE_OF",
		3: "COMBINATION_OF",
		4: "SET_OF",
		5: "REFERENCE_TYPE",
		6: "NOT_SET_OF",
	}
	CreateFlagReq_Family_value = map[string]int32{
		"UNIVERSAL_DISABLED": 0,
		"UNIVERSAL_ENABLED":  1,
		"PERCENTAGE_OF":      2,
		"COMBINATION_OF":     3,
		"SET_OF":             4,
		"REFERENCE_TYPE":     5,
		"NOT_SET_OF":         6,
	}
)

func (x CreateFlagReq_Family) Enum() *CreateFlagReq_Family {
	p := new(CreateFlagReq_Family)
	*p = x
	return p
}

func (x CreateFlagReq_Family) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateFlagReq_Family) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_flago_proto_enumTypes[0].Descriptor()
}

func (CreateFlagReq_Family) Type() protoreflect.EnumType {
	return &file_pkg_proto_flago_proto_enumTypes[0]
}

func (x CreateFlagReq_Family) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateFlagReq_Family.Descriptor instead.
func (CreateFlagReq_Family) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_flago_proto_rawDescGZIP(), []int{0, 0}
}

type CreateFlagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlagFamily CreateFlagReq_Family `protobuf:"varint,1,opt,name=flagFamily,proto3,enum=flago.CreateFlagReq_Family" json:"flagFamily,omitempty"`
	FlagData   []byte               `protobuf:"bytes,2,opt,name=flagData,proto3" json:"flagData,omitempty"`
	FlagReg    *FlagReq             `protobuf:"bytes,3,opt,name=flagReg,proto3" json:"flagReg,omitempty"`
}

func (x *CreateFlagReq) Reset() {
	*x = CreateFlagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_flago_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagReq) ProtoMessage() {}

func (x *CreateFlagReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_flago_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagReq.ProtoReflect.Descriptor instead.
func (*CreateFlagReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_flago_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFlagReq) GetFlagFamily() CreateFlagReq_Family {
	if x != nil {
		return x.FlagFamily
	}
	return CreateFlagReq_UNIVERSAL_DISABLED
}

func (x *CreateFlagReq) GetFlagData() []byte {
	if x != nil {
		return x.FlagData
	}
	return nil
}

func (x *CreateFlagReq) GetFlagReg() *FlagReq {
	if x != nil {
		return x.FlagReg
	}
	return nil
}

type GetFlagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlagData *FlagReq `protobuf:"bytes,1,opt,name=flagData,proto3" json:"flagData,omitempty"`
}

func (x *GetFlagReq) Reset() {
	*x = GetFlagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_flago_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagReq) ProtoMessage() {}

func (x *GetFlagReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_flago_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagReq.ProtoReflect.Descriptor instead.
func (*GetFlagReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_flago_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlagReq) GetFlagData() *FlagReq {
	if x != nil {
		return x.FlagData
	}
	return nil
}

type FlagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId   string `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerName string `protobuf:"bytes,2,opt,name=customerName,proto3" json:"customerName,omitempty"`
	Feature      string `protobuf:"bytes,3,opt,name=feature,proto3" json:"feature,omitempty"`
}

func (x *FlagReq) Reset() {
	*x = FlagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_flago_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagReq) ProtoMessage() {}

func (x *FlagReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_flago_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagReq.ProtoReflect.Descriptor instead.
func (*FlagReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_flago_proto_rawDescGZIP(), []int{2}
}

func (x *FlagReq) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FlagReq) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *FlagReq) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

type FlagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *FlagResp) Reset() {
	*x = FlagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_flago_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagResp) ProtoMessage() {}

func (x *FlagResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_flago_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagResp.ProtoReflect.Descriptor instead.
func (*FlagResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_flago_proto_rawDescGZIP(), []int{3}
}

func (x *FlagResp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_pkg_proto_flago_proto protoreflect.FileDescriptor

var file_pkg_proto_flago_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6c, 0x61, 0x67,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x0d,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x3b, 0x0a,
	0x0a, 0x66, 0x6c, 0x61, 0x67, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x0a,
	0x66, 0x6c, 0x61, 0x67, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c,
	0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x6c,
	0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x07, 0x66, 0x6c, 0x61, 0x67, 0x52, 0x65,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x2e,
	0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x52, 0x07, 0x66, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x67,
	0x22, 0x8e, 0x01, 0x0a, 0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x12, 0x55,
	0x4e, 0x49, 0x56, 0x45, 0x52, 0x53, 0x41, 0x4c, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x49, 0x56, 0x45, 0x52, 0x53, 0x41, 0x4c,
	0x5f, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x45,
	0x52, 0x43, 0x45, 0x4e, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x4f, 0x46, 0x10, 0x02, 0x12, 0x12, 0x0a,
	0x0e, 0x43, 0x4f, 0x4d, 0x42, 0x49, 0x4e, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x46, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x54, 0x5f, 0x4f, 0x46, 0x10, 0x04, 0x12, 0x12, 0x0a,
	0x0e, 0x52, 0x45, 0x46, 0x45, 0x52, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10,
	0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x4f, 0x46, 0x10,
	0x06, 0x22, 0x38, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x2a, 0x0a, 0x08, 0x66, 0x6c, 0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65,
	0x71, 0x52, 0x08, 0x66, 0x6c, 0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x07, 0x46,
	0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x24, 0x0a, 0x08, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x32, 0xd0, 0x01, 0x0a, 0x0c, 0x46,
	0x6c, 0x61, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x14, 0x2e, 0x66, 0x6c, 0x61, 0x67,
	0x6f, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x61, 0x67, 0x12, 0x11, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x67, 0x65, 0x74, 0x46, 0x6c,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x46, 0x6c,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x06, 0x4f, 0x6e, 0x46, 0x6c, 0x61, 0x67,
	0x12, 0x0e, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2a, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x0e, 0x2e, 0x66,
	0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x66,
	0x6c, 0x61, 0x67, 0x6f, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x69, 0x6f, 0x2f, 0x46, 0x6c, 0x61, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_flago_proto_rawDescOnce sync.Once
	file_pkg_proto_flago_proto_rawDescData = file_pkg_proto_flago_proto_rawDesc
)

func file_pkg_proto_flago_proto_rawDescGZIP() []byte {
	file_pkg_proto_flago_proto_rawDescOnce.Do(func() {
		file_pkg_proto_flago_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_flago_proto_rawDescData)
	})
	return file_pkg_proto_flago_proto_rawDescData
}

var file_pkg_proto_flago_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_flago_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_flago_proto_goTypes = []interface{}{
	(CreateFlagReq_Family)(0), // 0: flago.createFlagReq.Family
	(*CreateFlagReq)(nil),     // 1: flago.createFlagReq
	(*GetFlagReq)(nil),        // 2: flago.getFlagReq
	(*FlagReq)(nil),           // 3: flago.FlagReq
	(*FlagResp)(nil),          // 4: flago.FlagResp
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_pkg_proto_flago_proto_depIdxs = []int32{
	0, // 0: flago.createFlagReq.flagFamily:type_name -> flago.createFlagReq.Family
	3, // 1: flago.createFlagReq.flagReg:type_name -> flago.FlagReq
	3, // 2: flago.getFlagReq.flagData:type_name -> flago.FlagReq
	1, // 3: flago.FlagoService.CreateFlag:input_type -> flago.createFlagReq
	2, // 4: flago.FlagoService.GetFlag:input_type -> flago.getFlagReq
	3, // 5: flago.FlagoService.OnFlag:input_type -> flago.FlagReq
	3, // 6: flago.FlagoService.OffFlag:input_type -> flago.FlagReq
	5, // 7: flago.FlagoService.CreateFlag:output_type -> google.protobuf.Empty
	4, // 8: flago.FlagoService.GetFlag:output_type -> flago.FlagResp
	4, // 9: flago.FlagoService.OnFlag:output_type -> flago.FlagResp
	4, // 10: flago.FlagoService.OffFlag:output_type -> flago.FlagResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_flago_proto_init() }
func file_pkg_proto_flago_proto_init() {
	if File_pkg_proto_flago_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_flago_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_flago_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_flago_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_flago_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_flago_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_flago_proto_goTypes,
		DependencyIndexes: file_pkg_proto_flago_proto_depIdxs,
		EnumInfos:         file_pkg_proto_flago_proto_enumTypes,
		MessageInfos:      file_pkg_proto_flago_proto_msgTypes,
	}.Build()
	File_pkg_proto_flago_proto = out.File
	file_pkg_proto_flago_proto_rawDesc = nil
	file_pkg_proto_flago_proto_goTypes = nil
	file_pkg_proto_flago_proto_depIdxs = nil
}
